apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scaleconf
  labels:
    app: scaleconf  
  namespace: default  
spec:
  replicas: 1      
  template:
    metadata:
      labels:
        app: scaleconf
      name: scaleconf
    spec:
      containers:
      - env:               
        image: runcontainers-on.azurecr.io/samples/scaleconf:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        name: scaleconf        
      imagePullSecrets:
      - name: runcontainerskey